---
- hosts: localhost
  vars:
    rbenv:
      env: user
      version: v1.1.1
      default_ruby: 2.5.1
      rubies:
      - version: 2.5.1
  handlers:
    - name: ibus restart
      command: ibus restart
  # Install Ruby environment
  roles:
    - role: zzet.rbenv
      rbenv_users:
        - paul

  tasks:
    - command: lsb_release -cs
      register: distribution_release
      check_mode: no

    - set_fact:
        ansible_distribution_release: "{{ distribution_release.stdout }}"

    # apt install common packages
    - name: Install common packages
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      with_items: [sudo, rsync, curl, byobu, emacs, git, apt-transport-https, ca-certificates, bash-completion, python-pip, pass, htop, peek, sqlite3, ibus, im-config, pulseaudio, pulseaudio-module-bluetooth, pavucontrol, bluez, bluez-firmware, gnupg2, gnupg-agent, pinentry-curses, scdaemon, pcscd, yubikey-personalization, libusb-1.0-0-dev]
    - name: Install cheat python package
      pip:
        name: cheat

    # Install ibus-emoji (Emoji keyboard)
    - name: Fetch repostiory for ibus-uniemoji
      git:
        repo: "https://github.com/salty-horse/ibus-uniemoji.git"
        dest: ~/devel/ibus-uniemoji/
      become: true
      become_user: paul
    - name: Check existing ibus-uniemoji installation
      stat:
        path: /home/paul/devel/ibus-uniemoji/uniemoji.xml
      register: ibus_uniemoji
    - name: Install ibus-uniemoji
      make:
        chdir: /home/paul/devel/ibus-uniemoji
        target: install
      when: not ibus_uniemoji.stat.exists
      notify: ibus restart

    # Install stable version of Firefox
    - name: Check existing firefox
      stat:
        path: /opt/firefox/firefox
      register: firefox
    - name: Install stable Firefox instead of firefox-esr
      unarchive:
        src: https://download-installer.cdn.mozilla.net/pub/firefox/releases/61.0.2/linux-x86_64/en-US/firefox-61.0.2.tar.bz2
        dest: /opt/
        remote_src: yes
      when: not firefox.stat.exists
    - name: Create firefox desktop link
      copy:
        src: firefox.desktop
        dest: /usr/share/applications/firefox-stable.desktop
    - name: Uninstall firefox-esr
      apt:
        name: firefox-esr
        state: absent

    # Install Docker
    - name: Receive Docker gpg ke
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present
    - name: Add Docker repository
      apt_repository:
        repo: "deb [arch=amd64] https://download.docker.com/linux/debian {{ ansible_distribution_release }} stable"
        state: present
    - name: Install docker
      apt:
        name: docker-ce
        state: present
        update_cache: yes
        cache_valid_time: 86400

    # Install kubectl
    - name: Receive google cloud gpg key
      apt_key:
        url: https://packages.cloud.google.com/apt/doc/apt-key.gpg
        state: present
    - name: Add Kubernetes repository
      apt_repository:
        repo: "deb http://apt.kubernetes.io/ kubernetes-stretch main"
        state: present
    - name: Install kubectl
      apt:
        name: kubectl
        state: present
        update_cache: yes
        cache_valid_time: 86400

    # Install nextcloud desktop client
    - name: Receive nextcloud-devs gpg key
      apt_key:
        id: 1FCD77DD0DBEF5699AD2610160EE47FBAD3DD469
        keyserver: keyserver.ubuntu.com
        state: present
    - name: Add PPA nextcloud-devs
      apt_repository:
        repo: "deb http://ppa.launchpad.net/nextcloud-devs/client/ubuntu bionic main"
        state: present
    - name: Install nextcloud-client
      apt:
        name: nextcloud-client
        state: present
        update_cache: yes
        cache_valid_time: 86400

    # Install Weechat
    - name: Receive WeeChat gpg key
      apt_key:
        id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E
        keyserver: p80.pool.sks-keyservers.net
    - name: Add WeeChat repository
      apt_repository:
        repo: "deb https://weechat.org/debian {{ ansible_distribution_release }} main"
        state: present
    - name: Install weechat
      apt:
        name: "{{ item }}"
        state: present
        update_cache: yes
        cache_valid_time: 86400
      with_items: [weechat-curses, weechat-plugins, weechat-python, weechat-perl]
    - name: Install weeslack dependencies
      pip:
        name: websocket-client

    # Install custom Emacs configuration
    - name: Check existing emacs config
      stat:
        path: ~/.emacs.d
      become: true
      become_user: paul
      register: sym
    - name: Move emacs config if not a link
      copy:
        src: ~/.emacs.d
        dest: ~/.emacs.d.bak
      become: true
      become_user: paul
      when: sym.stat.islnk is defined and not sym.stat.islnk
    - name: Remove emacs config if not a link
      file:
        state: absent
        path: ~/.emacs.d
      become: true
      become_user: paul
      when: sym.stat.islnk is defined and not sym.stat.islnk
    - name: Install Paul s emacs config
      git:
        repo: 'https://github.com/paulrbr/emacs.d'
        dest: ~/.emacs.d.git
      become: true
      become_user: paul
    - name: Link emacs config
      file:
        state: link
        src: ~/.emacs.d.git
        dest:  ~/.emacs.d
      become: true
      become_user: paul

    # Install custom bash profile
    - name: Check existing profile
      stat:
        path: ~/.profile
      become: true
      become_user: paul
      register: sym
    - name: Install profile
      command: "curl -s https://raw.githubusercontent.com/paulRbr/profile/master/install | bash"
      become: true
      become_user: paul
      when: sym.stat.islnk is defined and not sym.stat.islnk

    # Install "$HOME" opt dir
    - name: Check existing /opt directory
      stat:
        path: /opt
      register: sym
    - name: Move /opt if not a link
      copy:
        src: /opt
        dest: /opt.bak
      when: sym.stat.islnk is defined and not sym.stat.islnk
    - name: Remove /opt if not a link
      file:
        state: absent
        path: /opt
      when: sym.stat.islnk is defined and not sym.stat.islnk
    - name: Link ~/opt
      file:
        state: link
        src: /home/paul/opt
        dest:  /opt

    # Setup ruby env (install common ruby gems)
    - name: Install ruby gems
      gem:
        name: "{{ item }}"
        state: present
      with_items: [bundler, rotp]
      become: true
      become_user: paul
