---
# Install Haskell Stack
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items: [haskell-stack]

- name: Upgrade Stack (Haskell)
  command: stack upgrade --binary-only

- name: Install hindent for Haskell formatting
  command: "stack install {{ item }}"
  with_items: [hindent, stylish-haskell]
  become: true
  become_user: paul

# Install NVM
- name: Get NVM installation script
  get_url:
    url: https://raw.githubusercontent.com/creationix/nvm/v0.33.11/install.sh
    dest: /tmp/nvm_install.sh
  register: nvm_script

- name: Install NVM
  command: sh /tmp/nvm_install.sh
  become: true
  become_user: paul

- name: Install node
  command: nvm install 8.9.3

# Install Yarn
- name: Receive YarnPKG gpg key
  apt_key:
    url: https://dl.yarnpkg.com/debian/pubkey.gpg
    state: present
    id: 11E9DE8848F2B65222AA75B8D1820DB22A11534E
    keyserver: p80.pool.sks-keyservers.net
- name: Add YarnPKG repository
  apt_repository:
    repo: "deb https://dl.yarnpkg.com/debian/ stable main"
    state: present
- name: Install yarn
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items: [yarn]
