---
# Install Haskell Stack
- name: Install common packages
  apt:
    name: "{{ item }}"
    state: present
    update_cache: yes
    cache_valid_time: 86400
  with_items: [haskell-stack]

- name: Upgrade Stack (Haskell)
  command: stack upgrade --binary-only

- name: Install hindent for Haskell formatting
  command: "stack install {{ item }}"
  with_items: [hindent, stylish-haskell]
  become: true
  become_user: paul
